## distilbert-Search engine

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('flipkart_com-ecommerce_sample.csv')

In [44]:
df.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [47]:
df["keywords"] = df['product_name'].astype('str')+" "+df['description'].astype('str')+" "+df['brand'].astype('str')

In [48]:
df.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  \
0  {"product_specification"=>[{"key"=>"Number of ...   
1  {"product_specification"=>[{"key"=>"Installati...   
2  {"product_specification"=>[{"key"=>"Ideal For"...   
3  {"product_specification"=>[{"key"=>"Number of ...   
4  {"product_specification"=>[{"key"=>"Pet Type",...   

                                            keywords  
0  Alisha Solid Women's Cycling Shorts Key Featur...  
1  FabHomeDecor Fabric Double Sofa Bed FabHomeDec...  
2  AW Bellies Key Features of AW Bellies Sandals ...  
3  Alisha Solid Women's Cycling Shorts Key Featur...  
4  Sicons All Purpose Arnica Dog Shampoo Specific...

In [51]:
import os
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
model = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

In [53]:
from ProText import gen, low, dig,stopw, lemma, stem, spell, clean_len, WCloud, countvec, tfidf     

In [89]:
df1 = df.copy()
df1.drop_duplicates(subset ="product_name", keep = "first", inplace = True)
df1.shape

(12676, 16)

In [90]:
df2 = df1.loc[:, df1.columns =='keywords']

In [91]:
df2.shape

(12676, 1)

In [92]:
df2['keywords'] = df2['keywords'].apply(gen).apply(low).apply(lemma).apply(lemma)

<ipython-input-92-e8eb4d53ce78>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['keywords'] = df2['keywords'].apply(gen).apply(low).apply(lemma).apply(lemma)


In [93]:
df2.head()

keywords
0  alisha solid woman s cycling short key feature...
1  fabhomedecor fabric double sofa bed fabhomedec...
2  aw belly key feature of aw belly sandal wedge ...
4  sicons all purpose arnica dog shampoo specific...
5  eternal gandhi super series crystal paper weig...

In [94]:
def find_similar(vector_representation, all_representations, k=1):
    similarity_matrix = cosine_similarity(vector_representation, all_representations)
    np.fill_diagonal(similarity_matrix, 0)
    similarities = similarity_matrix[0]
    if k == 1:
        return [np.argmax(similarities)]
    elif k is not None:
        return np.flip(similarities.argsort()[-k:][::1])

In [95]:
paragraph = df2.iloc[:, 0] # the first column values
embeddings_distilbert = model.encode(paragraph.values)

In [96]:
embeddings_distilbert[0].shape

(768,)

In [142]:
embeddings_distilbert

array([[ 0.26844123, -0.2441675 , -0.17085114, ...,  0.5240974 ,
        -0.44951478, -0.49505383],
       [ 0.1121587 ,  0.2147487 ,  0.7705068 , ...,  0.34144872,
        -0.00897184, -0.24200454],
       [ 0.25008872,  0.38942343, -0.00467586, ...,  0.2223864 ,
        -0.10822044, -0.10095298],
       ...,
       [-0.17841221,  0.15853165, -0.3563738 , ...,  0.6569144 ,
         0.09663271, -0.1779556 ],
       [ 0.14489675,  0.1452736 , -0.26556867, ...,  0.17621362,
        -0.40206805, -0.1991737 ],
       [-0.34795246,  0.3571229 ,  0.05968894, ...,  0.61978924,
         0.5101023 ,  0.62800676]], dtype=float32)

## Search for "girl baby clothing"

In [144]:
search_string = "girl baby clothing"
search_vect = model.encode([search_string])

In [145]:
K = 5 # no. of rows that has to be extracted
distilbert_similar_indexes = find_similar(search_vect, embeddings_distilbert, K)

In [146]:
distilbert_similar_indexes

array([ 6580,  7348, 12128,  7328, 11110], dtype=int64)

In [147]:
for i in distilbert_similar_indexes:
    print(i)

6580
7348
12128
7328
11110


In [148]:
paragraph.iloc[distilbert_similar_indexes]

9530     next step baby girl s layered dress next step ...
10651    next step baby girl s striped top pyjama set s...
18996    ucb baby girl s trouser specification of ucb b...
10623    mothercare t shirt specification of mothercare...
17623    kid village applique round neck casual girl s ...
Name: keywords, dtype: object

## Search for "Women clothing"

In [149]:
search_string = "women clothing"
search_vect = model.encode([search_string])

In [150]:
K = 5 # no. of rows that has to be extracted
distilbert_similar_indexes = find_similar(search_vect, embeddings_distilbert, K)

In [151]:
distilbert_similar_indexes

array([12607,  8423,  6806, 12369, 11167], dtype=int64)

In [152]:
paragraph.iloc[distilbert_similar_indexes]

19668    kytes woman s layered dress kytes woman s laye...
12481    seeyaar woman s striped casual shirt seeyaar w...
9909     twiq s a garment girl s tube black dress speci...
19318    atithee woman s top and skirt set key feature ...
17695    indirang sleeveless solid girl s jacket specif...
Name: keywords, dtype: object

In [154]:
search_string = "I am looking for girl baby clothing"col
search_vect = model.encode([search_string])

In [155]:
K = 5 # no. of rows that has to be extracted
distilbert_similar_indexes = find_similar(search_vect, embeddings_distilbert, K)

In [156]:
distilbert_similar_indexes

array([7348, 6812, 7308,  643, 7136], dtype=int64)

In [157]:
paragraph.iloc[distilbert_similar_indexes]

10651    next step baby girl s striped top pyjama set s...
9915     indirang baby girl s pyjama specification of i...
10590    next step baby girl s printed top pyjama set k...
934      mom and kid baby girl s printed blue grey top ...
10382    titrit baby girl s gathered dress key feature ...
Name: keywords, dtype: object